### ISSUE TITLE
No application indicator shows up on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by a1ecbr0wn** [tauri-apps/libappindicator-rs#30]
**Description**
With a fresh clone of the repository, on an up to date version of Ubuntu 20.04 LTS, default Gnome setup with Wayland WM I cannot get an icon to show up with the other app indicators that I have running.

**Steps To Reproduce**
1. `sudo apt install libappindicator3-dev`
2. `git clone git@github.com:tauri-apps/libappindicator-rs.git`
3. `cd libappindicator-rs`
4. `cargo run --example hello`

**Expected behavior**
I would expect to see the rust logo in the app indicator area at the top of my screen

**Screenshots**
![Screenshot from 2022-03-17 10-56-09](https://user-images.githubusercontent.com/12213854/158794939-ebdad9a1-75ed-41ef-8bcf-7106974ed6f1.png)

**Syslog**
If I use the default code, there is nothing that shows up in `var/log/syslog`.  However if I put the file extension `.png` on the name of the file, a three dot icon appears rather than the specified icon, and this is found in `/var/log/syslog`:

```log
Mar 17 10:54:01 computer ubuntu-appindicators@ubuntu.com[4149]: libappindicator test application, Impossible to lookup icon for 'rust-log.png-panel' in path /home/a1ecbr0wn/dev/libappindicator-rs/examples
Mar 17 10:54:01 computer ubuntu-appindicators@ubuntu.com[4149]: unable to update icon for libappindicator test application
```

**Platform and Versions (please complete the following information):**
OS: `Ubuntu 20.04.4 LTS`
Rustc: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] Yes, if someone can set me in the right direction debugging the issue
- [ ] No

**Comment by amrbashir** [comment]
This looks like a faulty icon. I just updated the example icon. Please try again.
